[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build-preview"
  
[[redirects]]
  from = "/post"
  to = "/contact"
  status = 200
  force = true # COMMENT: ensure that we always redirect


[[redirects]]
  from = "/contact"
  to = "https://api.netlify.com/api/v1/sites"
  status = 200
  force = true
  headers = {X-From = "Netlify" , Authorization = "Bearer a8659ef07d0c774682278387bd5edf8d1561936a731791afd4b6b261e7224691"} # COMMENT: add this header to the search request


